# ======================================================================
# ==      AI Voice Assistant for Cooking - Final Configuration        ==
# ======================================================================

# --- 0. Core Settings ---
database:
  url: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${RDS_HOSTNAME}:${DB_PORT}/${POSTGRES_DB}"

api_keys:
  openai: "${OPENAI_API_KEY}"
  youtube: "YOUR_YOUTUBE_API_KEY_HERE"
  reddit_client_id: "YOUR_REDDIT_CLIENT_ID"
  reddit_client_secret: "YOUR_REDDIT_CLIENT_SECRET"
  reddit_user_agent: "CookingAssistantScraper/1.0 by YourUsername"

rag:
  embedding_model: "text-embedding-3-small"
  completion_model: "gpt-4-turbo"

# --- 1. Data Sources ---
recipe_sites:
  indian:
    - "https://www.archanaskitchen.com"
    - "https://www.tarladalal.com"
    - "https://www.vegrecipesofindia.com"
    - "https://hebbarskitchen.com"
    - "https://www.manjulaskitchen.com"
    - "https://www.sanjeevkapoor.com"
    - "https://www.indianhealthyrecipes.com"
    - "https://ministryofcurry.com"
  pan_asian:
    - "https://www.chinasichuanfood.com"
    - "https://www.justonecookbook.com"
    - "https://hot-thai-kitchen.com"
    - "https://rasamalaysia.com"
    - "https://www.maangchi.com" # Korean
    - "https://thewoksoflife.com" # Chinese-American
    - "https://www.vietworldkitchen.com" # Vietnamese
  italian_mexican:
    - "https://www.giallozafferano.it"
    - "https://www.mexicanplease.com"
    - "https://cookieandkate.com"
    - "https://www.isabeleats.com" # Mexican
    - "https://www.skinnytaste.com" # Often features these cuisines
    - "https://sipandfeast.com" # Italian-American
  western_international:
    - "https://www.allrecipes.com"
    - "https://www.seriouseats.com"
    - "https://www.bonappetit.com"
    - "https://www.kingarthurbaking.com/recipes"
    - "https://smittenkitchen.com"
    - "https://www.foodandwine.com"
    - "https://sallysbakingaddiction.com"
    - "https://www.onceuponachef.com"

contextual_sources:
  social_media:
    instagram:
      enabled: true
      scrape_comments: true
      accounts:
        - "nishamadhulika"
        - "kabitaskitchen"
        - "ranveer.brar"
        - "hebbars.kitchen"
        - "bonappetitmag"
        - "seriouseats"
        - "sanjeevkapoor"
        - "food52"
        - "smittenkitchen"
        - "maangchi"
      hashtags: ["cookingfail", "kitchennightmare", "cookinghelp", "recipequestion", "burntfood", "bakingfail", "askchef", "cookingadvice"]
    facebook:
      enabled: false
      scrape_comments: true
      pages: ["RanveerBrarOfficial", "HebbarsKitchen", "SeriousEats", "NYTCooking"] # etc.
      groups: ["foodbloggersofindia", "chefathome"]

  youtube:
    scrape_comments: true
    max_results_per_channel: 30
    channels:
      indian: ["UCBFKdfGk_f_qf9S22i5Qp2g", "UCe1mJcsRr9Jal9vpaQfS14g", "UCPLeqiN-FFK_M-Q-sX-H-4g", "UCDi81b9G0j0iDDp3b0iGBpQ", "UC4w2b9_n0C-P88VR3GAl4pQ", "UC3P5Afsrkhy2lT_c0s1G2gQ"] # etc.
      pan_asian: ["UCCYc7s_pXp_d22a7g6Kq2aA", "UCp2_pQ0sE5so2uI92i3G1bg", "UC54SL_45d7-4w0H2m2_hb8g", "UC8EMp8n_la4f-pEaREy9qNQ"] # etc.
      italian_mexican: ["UCW_wx72fO_2i0gAq_3V3Lqg", "UCL1w6-zY2a-j-vH-5V_s-tQ", "UCJmG_8iZ4_u-bT-K9E72S1A", "UCTO2cT1HwNWBgE_3D4yvJgQ"] # etc.
      western: ["UCzH3iADRIq1IJlIXjfNgTpA", "UCAb2lksTv2r2_2a_2I426JA", "UCkY5ORCN22s3fbbqH32_Isw", "UCpprB-U_3_A-holD_yD2GqA", "UCT3v2w_3yG_g4g2s-2G_33w"] # etc.

  forums:
    reddit:
      enabled: true
      scrape_comments: true
      subreddits: ["Cooking", "AskCulinary", "IndianFood", "recipes", "Baking", "cookingforbeginners", "chefit", "KitchenConfidential", "whatscooking"] # etc.
    quora:
      enabled: true
      scrape_answers: true
      topics: ["Cooking", "Indian-Cooking", "Recipes", "Food", "Baking", "Spices", "Kitchen-Hacks", "Food-Preservation", "Culinary-Arts"] # etc.

# --- 2. Pipeline Configuration ---
scraping:
  delay_between_requests: 2
  max_retries: 3
  timeout: 30
  concurrent_workers: 4
  contextual_keywords: ["help", "problem", "mistake", "fix", "burnt", "undercooked", "overcooked", "salty", "bland", "curdled", "soggy", "substitute", "alternative", "why did", "how to", "what went wrong"] # etc.

processing:
  deduplication_similarity_threshold: 0.90
  auto_tagging:
    enabled: true
    strategy: "dynamic_tfidf_clustering"
    params: {max_tags_per_item: 10, min_word_length: 3, top_n_keywords_per_cluster: 5}

# --- 3. Vision & Image Configuration ---
vision_data:
  enabled: true
  yolo_model_path: "models/vision/yolov8_ingredients.pt"
  confidence_threshold: 0.6
  frame_sampling_interval: 3

images:
  download_enabled: true
  max_size_bytes: 5242880
  formats: ["jpg", "jpeg", "png"]

# --- 4. Data Storage Paths ---
storage:
  raw_data_path: "s3://your-cooking-app-bucket/data/raw"
  processed_data_path: "s3://your-cooking-app-bucket/data/processed"
  contextual_data_path: "s3://your-cooking-app-bucket/data/contextual"
  vision_data_path: "s3://your-cooking-app-bucket/data/vision"
  images_path: "s3://your-cooking-app-bucket/data/images"
  log_path: "s3://your-cooking-app-bucket/logs/pipeline.log"

# --- 5. Data Validation Rules ---
validation:
  recipe_entry:
    title: { "min_length": 5 }
    ingredients: { "min_count": 3, "max_count": 50 }
    instructions: { "min_count": 3, "max_count": 50 }
  contextual_entry:
    question: { "min_length": 15, "max_length": 500 }
    answer: { "min_length": 20, "max_length": 5000 }
    tags: { "min_count": 1 }
    language: { "accepted": ["en", "hi", "hi-en"] }

# --- 6. AI Model Training Configuration ---
training:
  enabled: true
  openai_base_model: "gpt-3.5-turbo"
  fine_tuned_model_id: "ft:gpt-3.5-turbo-xxxxxxxx"
  dataset_path: "data/processed/lang_tagged_scraped_contextual_posts.json"

# --- 7. Custom Vision Model Training ---
vision_training:
  enabled: true
  labeled_dataset_path: "data/vision/labeled_dataset"
  output_model_path: "models/vision/cooking_stage_classifier.pth"
  base_model: "efficientnet_b0"
  learning_rate: 0.001
  num_epochs: 10
  batch_size: 32